config/routes.rb
ChadJolly::Application.routes.draw do
  get '/uptime-ping' => proc { |env| [200, {}, ["OK"]] }
  root to: 'pages#home'
  get '/packers', to: 'pages#packers'
  get '/weather', to: 'pages#weather'
  get '/radio',  to: 'pages#radbuff'
  get '/radbuff', to: redirect('/radio')
  get '/errors', to: 'pages#errors'
  resources :passes

  get '/is_the_shitter_full', to: 'pages#is_the_shitter_full'
  post '/shitters_full', to: 'pages#shitter'

  # Stop the noisy rails logging for missed routes.
  get '/*all' => proc {|env| [404, {}, [] ]}, via: :all
end

app/models/full.rb
class Full
  def self.full
    Rails.cache.fetch("shitters_full")
  end

  def self.full!
    Rails.cache.write("shitters_full", true)
  end

  def self.reset!
    Rails.cache.write("shitters_full", false)
  end
end

app/models/pass.rb
class Pass < ActiveRecord::Base
  validates_presence_of :email
  validates_presence_of :billing_ref
  validates_presence_of :valid_until

  def self.create_month!(email:, billing_ref:)
    create!(
      email: email,
      billing_ref: billing_ref,
      valid_until: 1.month.from_now
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # https://github.com/roidrage/lograge
  def append_info_to_payload(payload)
    super
    payload[:request_id] = request.uuid
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:shitter]

  def home

  end

  def packers
    @page_title = "My Packers Season Tickets Story | Chad Jolly"
    @meta_description = "I've been on the Packers season ticket waiting list for 30 years. This is my story."

    @data_points = {
      'Chad' => [
        [2003, 714],
        [2004, 673],
        [2005, 656],
        [2006, 629],
        [2007, 607],
        [2008, 591],
        [2009, 544],
        [2010, 480],
        [2011, 448],
        [2012, 415]
      ],

      'Emily' => [
        [2003, 2652],
        [2004, 2589],
        [2005, 2552],
        [2006, 2497],
        [2007, 2443],
        [2008, 2357],
        [2009, 2217],
        [2010, 2081],
        [2011, 2000],
        [2012, 1949]
      ],

      'Amy' => [
        [2003, 2653],
        [2004, 2590],
        [2005, 2553],
        [2006, 2498],
        [2007, 2444],
        [2008, 2358],
        [2009, 2218],
        [2010, 2082],
        [2011, 2001],
        [2012, 1950]
      ]
    }
  end

  def weather
    @station_id = ENV['WEATHER_STATION_ID']
  end

  def radbuff
    @page_title = "Radio Sync | Sync Radio Broadcast to Action on TV"
    @meta_description = "A web app that allows you to listen to your favorite local sports radio broadcast and sync it to the action on the TV, eliminating the delay"
  end

  def shitter
    Full.full!
    head :ok
  end

  def is_the_shitter_full
    if params[:reset]
      Full.reset!
    end
  end

  def errors
    if params[:ua]
      Rails.logger.error %(at=error type=browser_not_supported desc="#{params[:ua]}")
    elsif params[:denied]
      Rails.logger.error %(at=error type=user_denied desc="#{params[:denied]}")
    end
    head :ok
  end
end

app/controllers/passes_controller.rb
class PassesController < ApplicationController
  def show
    @pass = Pass.find(params[:id])
    render 'pages/radbuff'
  end

  def create
    charge = create_stripe_charge

    if charge.paid
      pass = Pass.create_month!(email: params.fetch(:stripeEmail), billing_ref: charge.id)

      Rails.logger.info %(at=info source=stripe desc="Successful Charge #{charge.id}" request_id=#{request.uuid}")

      redirect_to pass
    else
      Rails.logger.error %(at=error source=stripe desc="Unsuccessful Charge. Token: #{params[:stripeToken]} Error: #{charge.failure_message}" request_id=#{request.uuid}")
      head :bad_request
    end
  end

  private

    def create_stripe_charge
      begin
        Stripe::Charge.create(
          amount: 500,
          currency: "usd",
          source: params.fetch(:stripeToken),
          description: "1 Month Pass ($5)"
        )
      rescue Stripe::StripeError => e
        require 'ostruct'
        OpenStruct.new(paid: false, failure_message: e.message)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
  def stripe_checkout_form
    form_tag passes_path do
      javascript_include_tag(
        "https://checkout.stripe.com/checkout.js",
        class: "stripe-button",
        data: {
          key: STRIPE_PUBLISHABLE_KEY,
          amount: 500,
          name: "Radio Sync",
          description: "1 Month Pass ($5)",
          locale: 'auto',
          zip_code: true,
          label: 'Buy Me A Beer'
        }
      )
    end
  end
end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18787523-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head
    %title= @page_title || "Chad Jolly"
    %meta{:name => 'description', :content => @meta_description || 'Programmer, Packers Fan.'}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}

    = stylesheet_link_tag('application')
    = javascript_include_tag('application')

    <link href='https://fonts.googleapis.com/css?family=Merriweather:900,900italic,300,300italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:900,300' rel='stylesheet' type='text/css'>

    = render 'layouts/analytics' if Rails.env.production?
  %body
    .site-wrap
      %header.site-header.px2.px-responsive
        .mt2.wrap
          .measure
            = link_to 'Chad Jolly', root_path
            %nav.site-nav.right
              = link_to 'github', 'https://github.com/cjolly'
              = link_to 'twitter', 'https://twitter.com/chadjolly'
              = link_to 'facebook', 'https://www.facebook.com/chad.a.jolly'
      .post.p2.p-responsive.wrap
        .measure
          .home
            .posts
              .post
                = yield

app/views/pages/home.html.haml
%p
  I work at
  = link_to('LAWgical', 'https://www.lawgical.com') + '.'
  We build web apps with Ruby on Rails and a handful of other cool web technologies.

%p
  I spend most of my time working on
  = link_to('ServeManager', 'https://www.servemanager.com') + ', '
  the best damn software out there for managing a process serving business.
%p
  I have an interesting story about being on the
  = link_to 'Green Bay Packers season tickets waiting list', packers_path
  for my entire life.

%p
  Do you like to listen to the local radio broadcast when watching football or baseball?
  I made a tool to #{link_to 'sync radio broadcasts to action on TV', radio_path}.

app/views/pages/is_the_shitter_full.html.haml
%h1 IS THE SHITTER FULL?

- if Full.full
  %h2 YES! take it to the backyard.
- else
  %h2 NO, bombs away.

app/views/pages/packers.html.haml
.hero-unit
  %h2 Packers Season Tickets
  %p An average of 33 people move off of the list every year. If this trend continues I'll have season tickets to Lambeau Field when I'm 45 years old, 15 years from now.


.container
  %p My parents put #{link_to 'me', root_path} on the packers season tickets waiting list when I was born #{distance_of_time_in_words_to_now(Date.parse('May 31, 1980'))} ago. I still don't have tickets. So, when the post card arrived in the mail today informing me that I was number 480 on the list I thought I should share this journey.

  - @data_points.each do |name, data|
    %table.table.table-striped
      %caption= name
      %thead
        %tr
          %th Year
          %th Position
          %th Change
      %tbody
        - data.each_with_index do |year_data, i|
          %tr
            %td= year_data.first
            %td= year_data.last
            %td= i > 0 ? data[i-1].last - year_data.last : '&nbsp;'.html_safe

  %h3 News
  %p= link_to 'Fox 11 News -- Packers host Lambeau construction tour', 'http://www.fox11online.com/dpp/news/local/green_bay/packers-host-lambeau-construction-tour?ref=scroller&categoryId=10001&status=true'
  %p= link_to 'WBAY -- Construction Update', 'http://www.wbay.com/category/169373/video-landing-page?clipId=6612036&topVideoCatNo=14980&autoStart=true'
  %p= link_to 'Packers stock sale could start as early as Nov. 15 (NFL.com)', 'http://www.nfl.com/news/story/09000d5d823ee5c9/article/packers-stock-sale-could-start-as-early-as-nov-15'
  %p= link_to 'Expansion Planned for Lambeau (NY Times)', 'http://www.nytimes.com/2011/08/26/sports/football/green-bay-packers-announce-expansion-plan-for-lambeau-field.html'
  %p= link_to "Packers announce plans for Lambeau Field's south, north end zones (Packers.com)", 'http://www.packers.com/news-and-events/article-1/Packers-announce-plans-for-Lambeau-Fields-south-north-end-zones/1df5d407-10c0-43fd-b12b-e87a632a8c11'
  %p= link_to "Sunday's Best Co - Great Fitting Tees!", "http://www.sundaysbestco.com/"

app/views/pages/radbuff.html.haml
%h2 Radio Sync
%p Mute the TV announcers and listen to the local radio broadcast with no delay, for a beer.
%ol#app
  %li Connect radio to line-in/mic port.
  %li
    #ensure
      = button_tag 'Start', id: 'js_mute'
      Can you hear radio on computer's speakers?
    #ensure_error{style: 'display:none;'}
      Acess to the microphone was denied. You'll need to enable it in settings.
      %ul
        %li= link_to 'Chrome Instructions', 'https://support.google.com/chrome/answer/2693767?hl=en', target: '_blank'
        %li= link_to 'FireFox Instructions', 'https://support.discordapp.com/hc/en-us/articles/204392448-How-do-I-enable-my-mic-in-Firefox-', target: '_blank'
  %li.controls#checkout{data: {pass_id: @pass.try(:id)}}
    - if @pass
      Thanks! Pass valid until
      %span#pass_valid_until{data: {date: @pass.valid_until.to_s(:iso8601)}}
        = @pass.valid_until.to_s(:long)
    - else
      = stripe_checkout_form
  %li.controls
    Use slider to sync radio audio to game action on TV.
    %br
    #js_slider_container
      = range_field 'dude', 'bro', in: 0..30, step: 0.1, value: 0, id: 'js_range', disabled: true, style: 'width: 75%'
    #js_delay{style: 'display:none'} Realtime
  %li.controls Enjoy game!

#browser_not_supported{style: 'display:none;'}
  %p Bummer. Your browser doesn't have the audio features necessary for Radio Sync.
  %p But wait, <strong>there's still hope!</strong>
  %p
    The latest version of
    %a{href: 'https://www.google.com/intl/en/chrome/browser/desktop/index.html'} Google Chrome
    or
    %a{href: 'https://www.mozilla.org/en-US/firefox/new/'} Firefox
    should work great. You may even have one of these already installed.
  %p You'll also need to be on a desktop computer, mobile browsers currently don't support these features, unfortunately.
  %p
    Stop back with one of those browsers and you should be good to go.

app/views/pages/weather.html.haml
%h2 Jolly Weather Station

<object width="600" height="400"><param name="movie" value="http://www.wunderground.com/swf/Rapid_Fire.swf?units=english&station=#{@station_id}" /><embed src="http://www.wunderground.com/swf/Rapid_Fire.swf?units=english&station=KWIGREEN51" type="application/x-shockwave-flash" width="600" height="400" /></object>